matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
	  - CXX=g++-5
	  - CC=gcc-5
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
	  - CXX=g++-6
	  - CC=gcc-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env:
	   - CXX=clang++-3.8
	   - CC=clang-3.8

# Enable C++ support
language: cpp
# Build steps
script:
   - make
#  - mkdir build
#- cd build
#- cmake .. && make