addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - clang-3.8

# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang-3.8
  - gcc-5
# Build steps
script:
   - make
#  - mkdir build
#- cd build
#- cmake .. && make